[package]
name = "palate"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
chrono = { version = "0.4.45", default-features = false, features = ["now", "serde"] }
color-eyre = "0.6.5"
foundation-configuration = { version = "0.1.0", path = "../foundation/configuration" }
foundation-http-server = { version = "0.1.0", path = "../foundation/http-server", features = ["metrics"] }
foundation-init = { version = "0.1.0", path = "../foundation/init", features = ["database", "metrics"] }
foundation-recurring-job = { version = "0.1.0", path = "../foundation/recurring-job" }
foundation-shutdown = { version = "0.1.0", path = "../foundation/shutdown" }
foundation-templating = { version = "0.1.0", path = "../foundation/templating" }
foundation-uid = { version = "0.1.0", path = "../foundation/uid", features = ["serde", "sqlx"] }
pulldown-cmark = "0.13.4"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls", "uuid", "chrono"] }
teloxide = { version = "0.17.0", default-features = false, features = ["rustls"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.7", features = ["fs", "trace"] }
tracing.workspace = true
uuid = { version = "1.26.1", features = ["serde", "v4"] }

[dev-dependencies]
http-body-util = "0.1.5"
mockito = "1.7.2"
serde_json = "1.0.151"
tower = "0.5.3"
