alb:
  addr: 0.0.0.0
  ports:
    https: 443
    tls: 853
  reconciliation: /reconcile
  tls:
    domains:
      dns.opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/dns.opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/dns.opentracker.app/privkey.pem
  mtls:
    anchor:
      location: s3
      bucket: configuration-68f6c7
      key: f2/anchor.pem
    domains:
      - dns.opentracker.app

secrets:
  private_key:
    location: s3
    bucket: configuration-68f6c7
    key: f2/private.key

services:
  dns-server:
    image: alexanderjackson/dns-server
    tag: 20260814-0900
    routes:
      - host: dns.opentracker.app
        port: 853
    replicas: 1
    volumes:
      config:
        source:
          location: s3
          bucket: configuration-68f6c7
          key: dns-server/config.yaml
        target: /app/config/dns-server.yaml
