CREATE TYPE exercise_variant AS ENUM (
	'Squat',
	'Bench',
	'Deadlift',
	'Other'
);

CREATE TABLE structured_exercise (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	workout_id UUID NOT NULL REFERENCES workouts(id),
	variant exercise_variant NOT NULL,
	description TEXT NOT NULL,
	weight REAL NOT NULL,
	reps INTEGER NOT NULL,
	sets INTEGER NOT NULL,
	rpe REAL
);

CREATE TABLE freeform_exercise (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	workout_id UUID NOT NULL REFERENCES workouts(id),
	variant exercise_variant NOT NULL,
	description TEXT NOT NULL,
	weight REAL NOT NULL,
	reps INTEGER NOT NULL,
	sets INTEGER NOT NULL,
	rpe REAL
);
