server:
  host: 127.0.0.1
  port: 8000

telemetry:
  enabled: false
  endpoint: "http://localhost:4318/v1/traces"

database:
  host: localhost
  port: 5432

  root:
    username: alex
    password: ""
    database: postgres

  application:
    username: todayblue
    password: test
    database: today
