server:
  host: 127.0.0.1
  port: 8000

telemetry:
  enabled: false
  endpoint: "http://localhost:4318/v1/traces"

metrics:
  endpoint: "http://localhost:9090/api/v1/otlp/v1/metrics"
  interval_seconds: 15

database:
  host: localhost
  port: 5432

  root:
    username: postgres
    password: test
    database: postgres

  application:
    username: todayblue
    password: test
    database: today
