server:
  host: 127.0.0.1
  port: 8000

database:
  host: localhost
  port: 5432

  root:
    username: alex
    password: ""
    database: postgres

  application:
    username: todayblue
    password: test
    database: today
