[package]
name = "foundation-logging"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
