server:
  host: 0.0.0.0
  port: 8000

base_url: https://palate.opentracker.app

schedule:
  weekday: Sat
  hour: 10
  minute: 0

openrouter:
  api_key: {{ kW9J6TRwe1qovmSNA17OmZ9IEY4BHA7feQ4DW2siXrBq23ZK+p9jAz+xccEaMAwuR86E0oQIdvAUdXN47D6KgNJ2MmJWY6K9SachmD43ajuJKoprd3ZgqqNE9/aTdtx/JIiai7DGRTek2c2Gwo5Tyc5R1WpWyJ9TMP6HYXrg6o9EruHKZXHLh+ZiKfjYAV3sQLmAeLJU7JfV546RU3ojyoqvuC4qlgt6xykl+1aswM8MQa+FQ1gzwJdhxHTSJIV8BxzDdS3b47ro59s9jK3Ri1zMUqyISkTtwD8kLWJApDFTmtsspe0LchDwYRphicv2gM7WA/JhezTvW1zznOvdIQ== }}
  model: anthropic/claude-haiku-5.5

telegram:
  bot_token: {{ MssCIkWql3FGXVs+Ig1cA547hMTOUKxQYJeemDQiYasqvSzrf/nSCuw4Aan6oleWzKXoQzIJoCNrIUyM9bDEFaVZqdd9k4uObLemizkADEPNYiS/MdkUW4N3IDjSVTnMXX3gZD8XxMj+vd8xJjW8m6cfW218RY/DQGqrksL/bNztdSBTeuVb5xrxmJIyUPFuwbJ1nqkbBXvldKPeMEMCuO+XkErIc4GuQMn7iyHgjchAAwz3E5LyzeX5mZ4oX1KKhDRVvuxhqXF+jqLEgj5hx4+qE+XFStzJP/Qm/URw46hW9YiUB1di2yo/CFfk4MIrhH2I+BY8oKq6Zv4z8vDarg== }}
  chat_id: "{{ IMPmPLoZO/n1QLphoi2VH9sgjmMwLmMdnG3wGPn+DEHuDftJVR47h/FtFK7jzJnOvJkt9kr0f5JUc287DBZtf3okFqfKur5rtfZajOf8I8w851fwU2CH/mzEYfLKkqKSqaqzDKi5J5FnibucoZJXiVVjJ+2YJ2wklZNOiCUeyx4A+0eewHcHm/RonFgsAcL0NAxw8V/FIOiLKA/VTVpPAr/5ZHa/sFz6guXWyNRZ5Dh/eTlElE8mzJzhuxRelAR5pgnpETP80bMcSoQVo3aJo2ww6dGx0MQ9CM0kDh+GbWU8wCchXn6Ol2UafMAnXpPkshU30hPZbbzaAPRj68H48A== }}"

database:
  host: rds.mesh.internal
  port: 5432

  root:
    username: "postgres"
    password: {{ N9MenLBlFq7s9my9rijw6FLrHw1YHzinbKNsGraJ78Dyh4SEzgiN6MBwzQNuCw2hdwIULo9U6e6i3a7sAKJ+9Xjg/egbZsrcGbnPDxzQWE4WIKWruJ8uiY5TpuTvXz8ogQ8mK+5J4AT2pEIZOlcjVQRkChm2SKYD0daay4SyaCbgJo3knCDVqJ11nfQv1WO8ltuzB30/1v0thHQK18N1RDkLYvOtn2Kc5IOCgsE6TDq3Y6EMcxhI4vM4o85ccEdOJpWqUf/fsy51+njmtpgj95hr5ZIj28FwvPphtdMf/xoClMFPdV6WTeqnDCuz/xuxzFz3t7Z/xq5Nw9W5fF3PpQ== }}
    database: "postgres"

  application:
    username: "palateblue"
    password: {{ rVEHt+dj9KC1iGelYxs0sDuhyA0xa6U/HZ1QwOeq+m/IHAiniOhtv4urw4pzbVRfjrbjUMOb1zRjXwrD+ER3kORk1+D4tv6ltdz8lEUHEla/GrtIkk7yFWsM6z73+huKvb4PFL+7u3HalvtO9npzKfg/rg6m9hfeJBnqHmSzHWVo3RH7YKMYVHo5+mqoy50JsW8ZVFbjoZlyWAOEe3FrfRHL8eXhkoqGZPpVpG2oTQXoNBqjSRlD4Fh8G7bLZAF/b/pfV7tZ+HYw/V+7CwnmaTKj3D1S6iwAmY/h0rVzQ/3mU+QVJEPl3J5wqhebYKP3Fr7VFaAW7BNBVjzwKcdp2Q== }}
    database: "palate"

metrics:
  endpoint: http://prometheus.mesh.internal/api/v1/otlp/v1/metrics
  interval_seconds: 30
