server:
  host: 0.0.0.0
  port: 4444

database:
  host: rds.mesh.internal
  port: 5432

  root:
    username: postgres
    password: {{ V7oyHSjgr8+eb6sgqQ+hcfO0GoBhfCxy4v0WCH2U6qxqoH3n9ddi+CpcT3TaNYBtIeTtWdX3XTKhGdvSOgyem/drpBla4CVvHqJHEQtLsSYcrm8IychI3Q7MQTscC8UyHNKdhl6F/buLd81lF1DH3NJxCggBfolmhDJlbfGWrz9EFSjUQqnuEByliCkfCXGiu5S1n0ydFjFeoXvHjQ+uSq1RLgrJDPWSZIQufUWa5+0d+XwuzL0o7XoNnwPsXKhpxKLFzrVk8bJGoz1M1OUmCJMi8dcLhSYdnVCaGdeNVmfB8+cS0g/9mQgGPUgDll8cI3m4Z9pxV+YH+uRvBZOEFw== }}
    database: postgres

  application:
    username: certmanagerblue
    password: {{ Tp+dmfqavVfXIWXlHsP3mp7uu9TcVrVXi5Ul2b9yF22Io/jRukScn+dJNug7tscDoUHccmodCYrIlkjqcY1YHMCPS8O0UvBZ5Szjm883koq9YTukskh3q2/X2BKaHGXW8ELZSTreLZ+/Y68R4fRBFAJDR+RiF0HL8XBGU0waEdyqwkTSv2dbAZ+rZSuruVImvz/OgVYn5t18umKxX5iZwjLKRKq7HVKkDMQ4daQvwI5nvw9pe5ZGNT/iXutBNZcZkOItFEuNN1S9WX6qPqmyfvqhVl256Qxhv8qy9Uh+UdnTgUvEJtgir++UfWKsO2AvJstNswt4shGuzGPrfHBeDA== }}
    database: certmanager

storage:
  bucket: configuration-68f6c7
  prefix: f2/certificates

acme:
  environment: production
  contact: alexanderjackson@protonmail.com

notify:
  url: https://certificates.opentracker.app
  path: /certificates
