on:
  pull_request:
    branches: ["master"]
    paths:
    - 'apps/foundation/**'
    - 'apps/today/**'

name: CI

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/today
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install SQLx CLI
        run: cargo install --debug sqlx-cli

      - name: Create database
        run: sqlx database create

      - name: Run migrations
        run: sqlx migrate run

      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run --manifest-path apps/today/Cargo.toml --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo fmt --manifest-path apps/today/Cargo.toml --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - run: cargo clippy --manifest-path apps/today/Cargo.toml -- -D warnings
